### ISSUE TITLE
Recommends `$env:PSModuleAnalysisCachePath` to be located in `/var/cache/microsoft/powershell` folder

### ISSUE THREAD

**Issue by kiazhi** [PowerShell/PowerShell-Docker#103]
Recommends the `$env:PSModuleAnalysisCachePath` variable uses `/var/cache/microsoft/powershell/PSModuleAnalysisCache/ModuleAnalysisCache` path instead of `/PSModuleAnalysisCache/ModuleAnalysisCache` path.

This is to respect the Linux Filesystem Hierarchy Standard defined in [5.5. /var/cache : Application cache data](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html)

#### Current `$env:PSModuleAnalysisCachePath` Path

```dockerfile
    # set a fixed location for the Module analysis cache
    PSModuleAnalysisCachePath=/PSModuleAnalysisCache/ModuleAnalysisCache
```

#### Recommended `$env:PSModuleAnalysisCachePath` Path

```dockerfile
    # Set up PowerShell module analysis cache path
    PSModuleAnalysisCachePath=/var/cache/microsoft/powershell/PSModuleAnalysisCache/ModuleAnalysisCache
```

#### Affected Dockerfiles:

1. release\preview\alpine\docker\Dockerfile
2. release\preview\centos7\docker\Dockerfile
3. release\preview\debian8\docker\Dockerfile
4. release\preview\debian9\docker\Dockerfile
5. release\preview\fedora27\docker\Dockerfile
6. release\preview\fedora28\docker\Dockerfile
7. release\preview\opensuse423\docker\Dockerfile
8. release\preview\ubuntu14.04\docker\Dockerfile
9. release\preview\ubuntu16.04\docker\Dockerfile
10. release\preview\ubuntu18.04\docker\Dockerfile
11. release\stable\alpine\docker\Dockerfile
12. release\stable\centos7\docker\Dockerfile
13. release\stable\debian8\docker\Dockerfile
14. release\stable\debian9\docker\Dockerfile
15. release\stable\fedora27\docker\Dockerfile
16. release\stable\fedora28\docker\Dockerfile
17. release\stable\opensuse423\docker\Dockerfile
18. release\stable\ubuntu14.04\docker\Dockerfile
19. release\stable\ubuntu16.04\docker\Dockerfile
20. release\stable\ubuntu18.04\docker\Dockerfile

**Comment by TravisEz13** [comment]
yes, we should respect the  Linux Filesystem Hierarchy Standard.

Normally this is a per user cache.  I don't think there is a good reason to keep it per user in the docker container.  We might want to add a comment or in a `/docs/DesignDecisions.md` in the repo about this decision.  Someone can always make another decision and alter our code a bit.
