### ISSUE TITLE
Windows 1809 nanoserver image has corrupted PATH

### ISSUE THREAD

**Issue by dtretyakov** [PowerShell/PowerShell-Docker#164]
## Steps to reproduce

The following command:
```
docker run --rm -it mcr.microsoft.com/powershell:nanoserver-1809 pwsh -Command Write-Host $env:Path
```
outputs `;C:\Program Files\PowerShell`

In the original `mcr.microsoft.com/windows/nanoserver:1809` image PATH is `C:\Windows\system32;C:\Windows;`

## Expected behavior

PATH is `C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell`

## Details

In the following PR https://github.com/PowerShell/PowerShell-Docker/pull/118 was mentioned that `setx` command does not work and was created Dockerfile where PATH is set like that:

```
ENV PATH="$PATH;${ProgramFiles}\PowerShell"
```

while `setx` command is working when executed under ContainerAdministrator like that:

```
# In order to set system PATH, ContainerAdministrator must be used
USER ContainerAdministrator 
RUN setx /M PATH "%PATH%;C:\Program Files\PowerShell"
USER ContainerUser
```

Originally from the [dockerfile for dotnet](https://github.com/dotnet/dotnet-docker/blob/master/2.2/sdk/nanoserver-1809/amd64/Dockerfile#L27-L30).

**Comment by dtretyakov** [comment]
@TravisEz13, also dotnet team is using this approach for nanoserver images starting from 1709:
https://github.com/dotnet/dotnet-docker/blob/master/2.2/sdk/nanoserver-1709/amd64/Dockerfile

In nanoserver sac2016 images `setx /M PATH` was working without admin rights requirement.

**Comment by TravisEz13** [comment]
`ContainerAdimistrator` is depreciated and the provided work around is not supported.

**Comment by TravisEz13** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements#nano-server-vs-windows-server-core
> Starting with Windows Server version 1709 applications run under a user context, so commands that require administrator privileges will fail. You can specify the container administrator account via the --user flag (i.e. docker run --user ContainerAdministrator) however in the future we intend to fully remove administrator accounts from NanoServer.

**Comment by TravisEz13** [comment]
I merged the change, but it won't be fixed until we release a new set of images.

**Comment by brianharwell** [comment]
When will new images be published?

**Comment by TravisEz13** [comment]
We publish new images at least once a month.

This change would have been published by March.

**Comment by brianharwell** [comment]
Do you know the image and tag?

**Comment by TravisEz13** [comment]
`mcr.microsoft.com/powershell:nanoserver-1809`

**Comment by Amitie10g** [comment]
Why this is closed as it has not been resolved?
PS: ltsc2019 is also affected.

**Comment by TravisEz13** [comment]
This was fixed, if it is broken again it regressed.  Please open a new issue.
