### ISSUE TITLE
fedora28 Failing

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell-Docker#170]
@kiazhi 
https://powershell.visualstudio.com/docker/_build/results?buildId=15659
(I made sure that this was not an issue with the PR it was running on)

**Comment by RDIL** [comment]
Never mind, it appears that the fedora mirrors are all offline.

**Comment by TravisEz13** [comment]
Are they back up now?

**Comment by RDIL** [comment]
Not sure

**Comment by TravisEz13** [comment]
Let's keep this open then

**Comment by TravisEz13** [comment]
verified this is resolved
