### ISSUE TITLE
ClearLinux Web cmdlet tests are failing

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#172]
https://powershell.visualstudio.com/docker/_build/results?buildId=15850&view=logs&jobId=60e5e444-2a4b-5d12-2458-36b8222e08ae&taskId=97b48e0a-f84a-564e-7ccf-14b7f1b35efe&lineStart=44&lineEnd=45&colStart=1&colEnd=1

**Comment by RDIL** [comment]
@kiazhi

**Comment by TravisEz13** [comment]
I disabled the tests in #171 so this is not urgent.

**Comment by RDIL** [comment]
Fixed on master
