### ISSUE TITLE
Clear Linux failing

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#192]
Continues on error is being enable to prevent it from failing CI

**Comment by TravisEz13** [comment]
Merged in #183

**Comment by RDIL** [comment]
The issue appears to be that the `libcrypto` `so` file can't be found, meaning the copy fails.

**Comment by kiazhi** [comment]
@RDIL The libcrypto.so.1.0.0 is needed.

Have you tried running your modified Dockerfile using the the build.ps1 script?

```powershell
./build.ps1 -Build -Name clearLinux -Channel community-stable
```

I updated the Dockerfile in PR #177 after I ran the build.ps1 script successfully without issue on local machine but when it is running in Azure DevOps CI environment it failed.

**Comment by RDIL** [comment]
@kiazhi  it is an issue on my local machine:
```dockerfile
Calling post-update helper scripts
Update took 7.0 seconds, 5 MB transferred
95 files were not in a pack
Update successful - System updated from version 31140 to version 31270
18 files removed
Removing intermediate container a39bc4ed5770
 ---> 234a5e9d8af7
Step 20/25 : COPY --from=installer-env ["/usr/lib64/libcrypto.so.1.0.0", "/usr/lib64/libcrypto.so.1.0.0"]
COPY failed: stat /var/lib/docker/overlay2/e63e8492fff0d6e9e21e46dd7541691d50f17fa887d8fe47aa3eaac9b42c9604/merged/usr/lib64/libcrypto.so.1.0.0: no such file or directory
```

**Comment by kiazhi** [comment]
@RDIL I need to revisit this ClearLinux distro again because that `libcrypto.so.1.0.0` file seems to be moving target (eg. goalposts) in their `cryptoprocessor-management` bundle. The last time I ran it, the `libcrypto.so.1.0.0` file is there but I think whoever maintain that `cryptoprocessor-management` bundle might have pull it out.

**Comment by RDIL** [comment]
I'm going to disable it in the community build until then so master passes.
