### ISSUE TITLE
Use slim image where possible

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#223]
example debian:9-slim

**Comment by RDIL** [comment]
I will do this in a few mins.  
(please assign me so I don’t forget)

**Comment by TravisEz13** [comment]
We should look at the other images and see if we can make the changes there, too.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Docker/blob/d93bbedb86b748923e0e762a410eefd602165754/release/preview/debian9/getLatestTag.ps1#L7

`stretch` needs to be changed to `stretch-slim`

and 
https://github.com/PowerShell/PowerShell-Docker/blob/d93bbedb86b748923e0e762a410eefd602165754/release/preview/debian9/getLatestTag.ps1#L14
needs to be change from `stretch-\d{8}[\.\d{1}]?` to `stretch-\d{8}[\.\d{1}]?-slim`

**Comment by TravisEz13** [comment]
Verified deb is the only image with slim image
