### ISSUE TITLE
Source image for openSUSE needs to be updated

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#226]
> This image has been deprecated in favor of the `opensuse/leap` and `opensuse/tumbleweed` images provided and maintained by the openSUSE Project release team.

leap is the equivalent of what we were using

**Comment by RDIL** [comment]
I can take care of this next week

**Comment by TravisEz13** [comment]
@RDIL  that works.  make sure to update the gettags script.

**Comment by TravisEz13** [comment]
@RDIL 	thanks!
