### ISSUE TITLE
Path Issues nanoserver 6.2.0-nanoserver-1809_kb4480116_amd64

### ISSUE THREAD

**Issue by TurtleBeach** [PowerShell/PowerShell-Docker#228]
## Steps to reproduce
Start a container based on the Powershell nanoserver image in title, making CMD the default shell and leave it (CMD) running.
When container starts, type pwsh to start Powershell

```powershell

```

## Expected behavior

```
Powershell should start

```

## Actual behavior

```
Powershell fails to start because C:\Program Files\Powershell is not in the path.

Also, a semicolon appears to be required at the end of the last path entry.

```

## Environment data

```sh
> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 133
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows 10 Pro Version 1809 (OS Build 17763.437)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 63.95GiB
Name: Iguana
ID: xxxxx
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 62
 System Time: 2019-05-06T14:27:40.4320753-05:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

```powershell
> $PSVersionTable
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
Please Provide a repro.  What image are you using?  What is the docker command line?

**Comment by TravisEz13** [comment]
Please add Repro steps.  What image are you using?  What is the docker command line?

**Comment by TurtleBeach** [comment]
I believe everything is in the post - just build a container based on what I think is the latest nanoserver with Power Shell image (see title), leaving CMD as the default shell and running when the container starts. Then (try to) start Powershell. It won't run unless path is updated in container or the full path to pwsh.exe is entered. Which I think is strange since the image is a Powershell image.

**Comment by TravisEz13** [comment]
If you are building a custom container, please provide the docker file and the build command.

**Comment by TurtleBeach** [comment]
I clicked the New Issue button on an issue from February referencing problems with path in Powershell Image. Seemed to be appropriate.

**Docker File:**
FROM mcr.microsoft.com/windows/nanoserver:1809-KB4493509-amd64
LABEL description = "A Container for testing Dockerfiles"
LABEL maintainer = "jack@neuralstudio.ai"

USER ContainerAdministrator
CMD echo Elvis is entering the building...  & cmd

**Docker Build**
D:\Docker\test2>docker build -t pstest .
Sending build context to Docker daemon   2.56kB
Step 1/5 : FROM mcr.microsoft.com/windows/nanoserver:1809-KB4493509-amd64
 ---> 0ffd0dc59703
Step 2/5 : LABEL description = "A Container for testing Dockerfiles"
 ---> Using cache
 ---> 12bf41b5e3ea
Step 3/5 : LABEL maintainer = "jack@neuralstudio.ai"
 ---> Using cache
 ---> 86e7328ccdef
Step 4/5 : USER ContainerAdministrator
 ---> Using cache
 ---> fa50ecf666f7
Step 5/5 : CMD echo Elvis is entering the building...  & cmd
 ---> Running in b134f714b9cc
Removing intermediate container b134f714b9cc
 ---> 09479fd1b7d4
Successfully built 09479fd1b7d4
Successfully tagged pstest:latest

**Docker Run**
D:\Docker\test2>docker run -it --rm pstest
Elvis is entering the building...
Microsoft Windows [Version 10.0.17763.437]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>pwsh
'pwsh' is not recognized as an internal or external command,
operable program or batch file.

C:\>path
PATH=C:\Windows\system32;C:\Windows;
C:\>exit
D:\Docker\test2>

**Comment by TravisEz13** [comment]
`NanoServer` has no PowerShell 

Update this
`FROM mcr.microsoft.com/windows/nanoserver:1809-KB4493509-amd64`
to 
`FROM mcr.microsoft.com/powershell:6.2.0-nanoserver-1809_kb4480116_amd64`

Current tags can be found here:
https://hub.docker.com/_/microsoft-powershell

The full tag listing can be found here:
https://mcr.microsoft.com/v2/powershell/tags/list

**Comment by TurtleBeach** [comment]
Travis,

Apologies, that in my haste to create a simple Docker file I referenced the wrong image. I don’t want to create a new issue, but I am in fact using the Powershell image you referenced in my “working test” container.

The anomaly that drove me up the wall is actually related to whether or not there is a trailing semicolon when the path is set. Please bear with me – and trust me when I say that the only difference in running two different containers is whether or not the semicolon is added to a “Set” command in the Docker file. Powershell will run or not, depending on that difference. To wit:

** LINE IN Dockerfile: NOTE NO SEMI-COLON AFTER %PATH%
RUN echo @set PATH=%JRE_INSTALL_PATH%\bin;%PATH% >setpath.bat

** Running container **
Elvis is entering the building...

C:\>cd  c:\neuralworks
Microsoft Windows [Version 10.0.17763.253]
(c) 2018 Microsoft Corporation. All rights reserved.

c:\neuralworks>path (I typed this after container starts)
PATH=c:\jdk1.8.0_181\bin;C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell

c:\neuralworks>pwsh (I typed this after container starts)
'pwsh' is not recognized as an internal or external command,
operable program or batch file.

** EXACT SAME Dockerfile EXCEPT SEMI-COLON after last %PATH% in the set command
RUN echo @set PATH=%JRE_INSTALL_PATH%\bin;%PATH%; >setpath.bat

** Running container **
Elvis is entering the building...

C:\>cd  c:\neuralworks
Microsoft Windows [Version 10.0.17763.253]
(c) 2018 Microsoft Corporation. All rights reserved.

c:\neuralworks>path (I typed this after container starts)
PATH=c:\jdk1.8.0_181\bin;C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;

c:\neuralworks>pwsh (I typed this after container starts)
PowerShell 6.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\neuralworks> get-process

NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
------    -----      -----     ------      --  -- -----------
      6     1.07       4.48       0.02    1092   1 CExecSvc
      5     3.36       3.78       0.02    1216   1 cmd
      5     4.29       3.77       0.02    1396   1 cmd
      6     1.05       4.02       0.02    1200   1 conhost
      5     0.94       3.69       0.02    1384   1 conhost
      7     0.81       2.13       0.00     992   1 csrss
      0     0.05       0.01       0.00       0   0 Idle
     30   136.65     139.30      11.17    1372   1 java
     19     3.60      10.95       0.13     248   1 lsass
     46    33.44      61.80       0.91    1912   1 pwsh
      9     1.64       5.01       0.09     256   1 services
      4     0.47       1.12       0.02     968   0 smss
      8     1.69       5.80       0.03     368   1 svchost
     14     1.87       6.36       0.05     464   1 svchost
     12     2.89       9.88       0.11    1028   1 svchost
      7     1.49       4.73       0.02    1068   1 svchost
     15     5.55      10.26       0.11    1132   1 svchost
     25     3.54      10.18       0.13    1208   1 svchost
     18     5.61      16.45       0.14    1468   1 svchost
      0     0.15       0.15       0.67       4   0 System
      8     1.06       4.05       0.02      60   1 wininit

PS C:\neuralworks> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

While obviously I have figured out how to work around this, it drove me crazy when I was appending the path for the JDK to %PATH% in the batch file, and Java wasn’t staring. So I prepended the JDK path, and then Powershell stopped working.
It strikes me as strange that the semi-colon is required for the set Path command – and I don’t think I have seen this on any other Windows.

Cheers,
Jack
____________________________
Jack Copper
Managing Director
NeuralStudio SEZC
Strathvale House, 90 N Church St
PO Box 10315 Grand Cayman KY1-1003
Cayman Islands
https://neuralstudio.ai
Direct:  +1 (345) 815-3930
Mobile: +1 (345) 925-8459

SKYPE:  jack-copper
____________________________
This communication is for use by the intended recipient(s) only and contains
information that may be privileged, confidential or copyrighted under
applicable law.  If you are not an intended recipient, you are hereby
formally notified that any use, copying or distribution of this e-mail,
in whole or in part, is strictly prohibited.  Please notify the sender
by return e-mail and delete this e-mail from your system.  This e-mail
does not constitute a consent to the use of sender's contact information
for direct marketing purposes or for transfers of data to third parties.
**************************************************************************

**Comment by TravisEz13** [comment]
I'm sorry.  I'm not able to repro your problem.

```
>docker run --rm -i mcr.microsoft.com/powershell:6.2.0-nanoserver-1809_kb4480116_amd64 cmd
Microsoft Windows [Version 10.0.17763.253]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>pwsh
pwsh
PowerShell 6.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\>
```

**Comment by TurtleBeach** [comment]
Travis,

It appears I still have not been clear. The issue arises when, during container creation, a batch file is generated which, when executed in the container on container startup,  sets the path to the Java JDK. Please look carefully at my prior e-mail.

(1) if a path is APPENDED to the current path (e.g., %PATH%;<new-path>), and the (new appended) path does not have a trailing ; (semicolon), the appended path will NOT be recognized after the batch file is run inside the container
(2) if the new path is PRE-PENDED to the existing path (e.g., <new-path>;%PATH% - and in this case a semicolon is in fact required between <new-path> and %PATH%), the “C:\Program Files\Powershell” folder in the original path no longer has a trailing semicolon; the path to Powershell is not recognized and so Powershell will not start when just “pwsh” is typed (without the full path to the executable).

Original path as in the Powershell nanoserver image:
C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;       (NOTE the original path, when displayed, has a trailing semicolon, and without any other operations/changes to PATH, Powershell will start, as you demonstrated)

HOWEVER, if in a container a batch file executes on startup and updates the path:
set path=c:\jdk1.8.0_181\bin;%PATH%                 (NOTE in this case the batch file does not add a trailing semicolon; the %PATH% expansion results in the original trailing semicolon being dropped, and the resulting path is:

c:\jdk1.8.0_181;C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell       (NOTE there is NO trailing semicolon, and Powershell will NOT start if pwsh is typed)

I discovered eventually stumbled on the alternative - append a semicolon to the set path=c:\jdk1.8.0_181\bin;%PATH%;  in the batch file, and then Powershell will start as expected and Java.exe is in the path. The final path in the container as displayed is:
c:\jdk1.8.0_181;C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;      (NOTE in this case there IS a trailing semicolon, and Powershell will start if pwsh is typed)

I do not think that a semicolon is required after the last element in a path on other versions of  Windows, so I am surprised it is required by nanoserver with Powershell (I have not looked at other Windows container images).

Hopefully the scenario is now clear. Someone may decide it is not worth fixing, but then I think it ought to be clearly documented.
Jack
____________________________
Jack Copper
Managing Director
NeuralStudio SEZC
Strathvale House, 90 N Church St
PO Box 10315 Grand Cayman KY1-1003
Cayman Islands
https://neuralstudio.ai
Direct:  +1 (345) 815-3930
Mobile: +1 (345) 925-8459

SKYPE:  jack-copper
____________________________
This communication is for use by the intended recipient(s) only and contains
information that may be privileged, confidential or copyrighted under
applicable law.  If you are not an intended recipient, you are hereby
formally notified that any use, copying or distribution of this e-mail,
in whole or in part, is strictly prohibited.  Please notify the sender
by return e-mail and delete this e-mail from your system.  This e-mail
does not constitute a consent to the use of sender's contact information
for direct marketing purposes or for transfers of data to third parties.
**************************************************************************

**Comment by TravisEz13** [comment]
@TurtleBeach What batch file?  Who is providing this batch file?  You should work with the team that is providing this batch file.

**Comment by TurtleBeach** [comment]
Travis,

I wrote the batch file. I wrote the Docker file. I create a container which needs Java, and thus I need to set the path for Java. And Set Path in a nanoserver image is behaving oddly. I am sorry, but I don’t think I can improve on my explanations.

Jack
____________________________
Jack Copper
Managing Director
NeuralStudio SEZC
Strathvale House, 90 N Church St
PO Box 10315 Grand Cayman KY1-1003
Cayman Islands
https://neuralstudio.ai
Direct:  +1 (345) 815-3930
Mobile: +1 (345) 925-8459

SKYPE:  jack-copper
____________________________
This communication is for use by the intended recipient(s) only and contains
information that may be privileged, confidential or copyrighted under
applicable law.  If you are not an intended recipient, you are hereby
formally notified that any use, copying or distribution of this e-mail,
in whole or in part, is strictly prohibited.  Please notify the sender
by return e-mail and delete this e-mail from your system.  This e-mail
does not constitute a consent to the use of sender's contact information
for direct marketing purposes or for transfers of data to third parties.
**************************************************************************

**Comment by TravisEz13** [comment]
Then, please update the batch file to add a semicolon before the end of the path.  There is nothing wrong with the current path.

**Comment by TravisEz13** [comment]
I've created a PR, but technically this is not a bug.  This is an enhancement.  We are adding a feature where you can append to the path without determining if there is already a trailing semicolon.

We should be able to release this in this months release cycle, which should occur next week.

**Comment by TurtleBeach** [comment]
Yes, I know I can do that (and have done that). BUT, as I have been trying to communicate, the behavior on nanoserver is DIFFERENT from the behavior on other Windows (e.g., I just checked on Windows 10 Pro):

C:\Users\Admin>

C:\Users\Admin>path
PATH=C:\ProgramData\DockerDesktop\version-bin;<ALL INTERMEDIATE ENTRIES REMOVED>%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;          <NOTE TRAILING ;>

C:\Users\Admin>set path=c:\neuralstudio;%PATH%                <NOTE prepending a new path to the current path>

C:\Users\Admin>path
PATH=c:\neuralstudio;C:\ProgramData\DockerDesktop\version-bin; <ALL INTERMEDIATE ENTRIES REMOVED>%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;         <NOTE TRAILING ; still appears here – but this is NOT the behavior on nanoserver – and it caused me a lot of grief because the last place I thought to look for the error I was seeing was in setting the PATH – which has been in Windows since Windows 3.11 – which I am old enough to have used and written software for>

C:\Users\Admin>

Hence my belief – either nanoserver should be fixed or this anomalous behavior should be documented.

I will not bother you any more about this.

Cheers,
Jack
____________________________
Jack Copper
Managing Director
NeuralStudio SEZC
Strathvale House, 90 N Church St
PO Box 10315 Grand Cayman KY1-1003
Cayman Islands
https://neuralstudio.ai
Direct:  +1 (345) 815-3930
Mobile: +1 (345) 925-8459

SKYPE:  jack-copper
____________________________
This communication is for use by the intended recipient(s) only and contains
information that may be privileged, confidential or copyrighted under
applicable law.  If you are not an intended recipient, you are hereby
formally notified that any use, copying or distribution of this e-mail,
in whole or in part, is strictly prohibited.  Please notify the sender
by return e-mail and delete this e-mail from your system.  This e-mail
does not constitute a consent to the use of sender's contact information
for direct marketing purposes or for transfers of data to third parties.
**************************************************************************

**Comment by TravisEz13** [comment]
See https://github.com/PowerShell/PowerShell-Docker/issues/228#issuecomment-489864388
