### ISSUE TITLE
SetX is not persisting environmental settings on 1809 images (works on 1803)

### ISSUE THREAD

**Issue by MattGal** [PowerShell/PowerShell-Docker#231]
## Steps to reproduce

Build this dockerfile based off your image:
```
FROM mcr.microsoft.com/powershell:6.2.0-nanoserver-1809

SHELL ["cmd", "/S", "/C"]
USER ContainerAdministrator
ENTRYPOINT C:\Windows\System32\cmd.exe

RUN curl -SL --output %TEMP%\python.zip https://www.nuget.org/api/v2/package/python/3.7.3 \
    && md C:\Python C:\PythonTemp \
    && tar -zxf %TEMP%\python.zip -C C:\PythonTemp \
    && xcopy /s c:\PythonTemp\tools C:\Python \
    && rd /s /q c:\PythonTemp \
    && del /q %TEMP%\python.zip

RUN setx /M PATH "%PATH%;C:\Program Files\PowerShell\;C:\Python;C:\python\scripts" \
    && setx /M PYTHONPATH "C:\Python\Lib;C:\Python\DLLs;"

RUN python -m pip install --upgrade pip
```

## Expected behavior

```none
Installs Python 3 on nano and upgrades pip
```

## Actual behavior

```none
Crashes because `C:\python`'s not on the path
```

## Environment data

```sh
> docker info
```

```powershell
> $PSVersionTable
```

**Comment by TravisEz13** [comment]
`setx` is nanoserver feature.  Please file an issue in uservoice:  https://windowsserver.uservoice.com/forums/295047-general-feedback

BTW, I've already filed this issue internally.

**Comment by TravisEz13** [comment]
We did find a workaround, but I know this workaround did not work in older versions of nanoserver:
https://github.com/PowerShell/PowerShell-Docker/blob/5d12bb11a32280cecd3cd74e51c8618687bc4943/release/preview/nanoserver1809/docker/Dockerfile#L73

**Comment by TravisEz13** [comment]
Also, see https://github.com/PowerShell/PowerShell-Docker/issues/164
