### ISSUE TITLE
Powershell nanoserver image missing VS2017 runtime redistributables

### ISSUE THREAD

**Issue by TurtleBeach** [PowerShell/PowerShell-Docker#234]
## Steps to reproduce
download latest nanoserver image with powershell
```
FROM mcr.microsoft.com/powershell:6.2.1-nanoserver-1809_kb4480116_amd64

```
Create a container with application or DLLs built using VS2017.
## Expected behavior
The application should run in container. At this point in time I would expect nanoserver image to have the VS2017 redistributable DLLs (vcruntime140.dll, concert140.dll, etc.) in Windows\System32
```none

```

## Actual behavior
Runtime DLLs are missing so applications built with VS2017 will not run.
```none

```

## Environment data

```sh
> docker info
```

```powershell
> $PSVersionTable
```

**Comment by RDIL** [comment]
Can reproduce

**Comment by TravisEz13** [comment]
For this you should use the dotnet-sdk image, which now in 3.0 includes PowerShell.

https://hub.docker.com/_/microsoft-dotnet-core-sdk

**Comment by TravisEz13** [comment]
The other option is to build an image which includes the files you need.  The VS2017 runtime redistributable are not required for PowerShell Core and would greatly increase the size of the image.

**Comment by TurtleBeach** [comment]
@TravisEz13 Thanks for the response. I did in fact add VS2017 redist as part building the container. But I do still find it puzzling that VS2013 runtime DLLs (for C/C++ projects) are included, but not VS2017 runtime DLLs (would add a little over 1 MB to image). Maybe the larger question is, what are the various images for, and what do they contain? Is a "Powershell" image intended ONLY for use by Powershell scripts? If so, could that not be documented? I chose a PS image because a couple of tasks that ultimately I will need performed looked like they could be easily handled by Powershell, rather than putting the tasks in Java code, which comprises the bulk of the application.

I have since discovered that Powershell itself is missing a lot of functionality - which it seems to me should be documented, rather than requiring developers to empirically discover what is there and what is not.

Further (acknowledging not specifically related to PS), it seems that most current windows images (I have not tried them all, but a good cross section) either omitted or broke some internal dns resolution mechanism. Code which accesses Azure Key Vault and Azure table storage using standard Azure libraries fails to work on various recent servercore and nanoserver images, with or without Powershell, running in an Azure Container Group/Instance, but does work in containers using1607 based images (and of course the code also works locally stand-alone and within a Docker container). This seems to me to be such a fundamental generic use case (accessing Azure resources from Windows containers), that it boggles the mind that it is broken in recent releases.

That said, I will look at the dotnet core image, which from the name may be more suited for running custom software on top of the OS.
Jack

**Comment by TravisEz13** [comment]
We only add runtime DLLs required by PowerShell.  

Missing Windows functionality should be filed with the Windows team.

**Comment by TravisEz13** [comment]
I filed https://github.com/PowerShell/PowerShell-Docker/issues/235 to document the purpose of the images.  The images are only intended to run built-in PowerShell functionality.  If you want to run other functionality, you may need to extend the image.  That is why the Dockerfiles are published.  Docker also allows you to build on top of our images.
