### ISSUE TITLE
Add image for ClearLinux

### ISSUE THREAD

**Issue by robertbaker** [PowerShell/PowerShell-Docker#253]
Please add a docker image for ClearLinux once https://github.com/PowerShell/PowerShell/issues/10261
and https://github.com/dotnet/core/issues/3124 are completed

**Comment by TravisEz13** [comment]
This image already exists and is only community supported because DotNet does not support the Distribution

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Docker/issues/192
