### ISSUE TITLE
Can't use Enter-PSSession

### ISSUE THREAD

**Issue by cdarais** [PowerShell/PowerShell-Docker#259]
I can't get PSSessions to work. Maybe i'm just don't know how to do it? I can't find anything on forums with this problem... so Here we go

## Steps to reproduce

docker exec -it  <powershell container> pwsh
PS /> Enter-PSSession -ComputerName "computer" -Credential "credentials"

## Expected behavior

At this point I should be in a PSSession on the computer but instead I get this error

## Actual behavior

At line:1 char:1
Enter-PSSession -ComputerName "computer" -Credential  …
CategoryInfo          : InvalidArgument: ("computer":String) [Enter-PSSession], PSInvalidOperationException
FullyQualifiedErrorId : CreateRemoteRunspaceFailed

----------

PS /> $PSVersionTable
Name                           Value
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

----------

docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by RDIL** [comment]
I think remoting was disabled for some reason.  Cc @PaulHigin

**Comment by cdarais** [comment]
Hmmmm any idea why? That is one of the most useful powershell features imo

**Comment by TravisEz13** [comment]
@cdarais What computer are you trying to remote into?

**Comment by TravisEz13** [comment]
`-ComputerName` is for windows remoting `-HostName` is for SSH remoting.   
The docs are here:  https://docs.microsoft.com/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6

**Comment by cdarais** [comment]
A number of computers on a domain. One is named inf-net01

**Comment by TravisEz13** [comment]
Are they windows or Linux?  Do you want to use WS-Man remoting or SSH remoting?
