### ISSUE TITLE
Ubuntu 19.04 image

### ISSUE THREAD

**Issue by Pr0methean** [PowerShell/PowerShell-Docker#265]
Ubuntu 19.04 currently has no Powershell Docker image, and the template for https://github.com/PowerShell/PowerShell/issues/10394 indicates that one is needed to create the Ubuntu package.

**Comment by TravisEz13** [comment]
This is an interim release per Ubuntu (https://ubuntu.com/about/release-cycle) . We don't support interim releases.

**Comment by TravisEz13** [comment]
Feel free to add a community support image.
