### ISSUE TITLE
ParrotSec is failing

### ISSUE THREAD

**Issue by kiazhi** [PowerShell/PowerShell-Docker#289]
ParrotSec/Parrot container image building is failing.

**Comment by RDIL** [comment]
Still an issue: https://dev.azure.com/tplunk/docker/_build/results?buildId=1982

**Comment by kiazhi** [comment]
hmm... interesting... 🤔   Why did `latest` got changed to `4`? There isn't a tag for it from parrot repo in docker hub since `4.0` is released till `4.6` / `latest`. 😄  @TravisEz13 

https://github.com/TravisEz13/PowerShell-Docker/blob/3e8c590ec29148179acab3b2b3cf4cea5dcc0d5b/release/community-stable/parrot/getLatestTag.ps1#L7

```text
@(Unable to find image 'pshorg/powershellcommunity:6.2.3-parrot-4' locally
```
 The following line above was found in the link below:

https://dev.azure.com/tplunk/docker/_build/results?buildId=1982&view=logs&jobId=65c65cc0-3a8c-509a-fd57-eef971b6d091&taskId=6268f428-4a66-514f-dfd4-a4f97518a4c2&lineStart=168&lineEnd=168&colStart=37&colEnd=100

**Comment by RDIL** [comment]
👍 I see where this started, and I can see why it happened, so we should find a way to allow both solutions.

**Comment by TravisEz13** [comment]
my change was because NOTHING was building...   I just don't have a lot of time to look at the community images.
I fixed it to cause something to build and fixed the engineering system to detect the issues in the future.  
I gave up on fixing parrot because it was taking too long.

**Comment by RDIL** [comment]
I see.

**Comment by kiazhi** [comment]
Hmm... I tried updating it to `latest` and seems to be having issue... I guess I have been away from this repo for too long. 😄

**Comment by RDIL** [comment]
We're refactoring the build system this week too 😄

**Comment by kiazhi** [comment]
> We're refactoring the build system this week too 😄

Ok. I will take a look after the refactoring.

**Comment by TravisEz13** [comment]
I **highly** suspect that the refactoring will take longer that a week unless you take a less ambitious approach than you initially suggested.  And, any refactoring will probably need to wait until after the 7.0 release.

**Comment by RDIL** [comment]
Don't worry, I'm not doing that much.  

We should also find a time to zoom

**Comment by RDIL** [comment]
@kiazhi I think it’s safe to say that the refactoring isn’t really going to start until me and @TravisEz13 come up with a plan for it, so feel free to do it now.

**Comment by RDIL** [comment]
Yeah no its not starting anytime soon

**Comment by TravisEz13** [comment]
@kiazhi  tell us if you start to work on this and I'll reassign the issue.  Assigned is supposed to mean actively working on the issue.

**Comment by kiazhi** [comment]
@TravisEz13  this is fixed and up to date now.
