### ISSUE TITLE
Add ARM image to build

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#296]
You can run PowerShell Core in a Docker container on a ARM device, such as a Raspberry Pi. There is not currently a pre-built container image published to a public repository, such as Docker Hub. However, you can build your own container image by downloading the `Dockerfile` for [PowerShell Core on ARM](https://github.com/PowerShell/PowerShell-Docker/blob/master/release/stable/arm32v7/docker/Dockerfile).
 

 
It looks like we can build this image when I checked today.

```
# Build the container image, using the current directory as the build context
docker build --tag powershell:arm32v7 .
# Run a new PowerShell Core container
docker run --rm --interactive --tty powershell:arm32v7
```

**Comment by TravisEz13** [comment]
@RDIL or @kiazhi  This image builds.  Do you want to try adding it to the Build/CI system.  I'm sure tests will have issues, you can leave that to me if you want.

**Comment by kiazhi** [comment]
@TravisEz13 I think having ARM in Build/CI system is a good addition. I have no doubt on @pcgeek86 (Trevor) contribution.

**Comment by TravisEz13** [comment]
The main issue is that the files for the build system, like metadata.json and gettags.ps1 where not added.

**Comment by RDIL** [comment]
I can take care of it within the next 2 weeks.

**Comment by pcgeek86** [comment]
@TravisEz13 I'd be happy to add these files, but you guys know your build system much better than me. Not sure I'm the best person to update it. It would take me a lot longer and pestering you with questions about how to add new container image builds.

**Comment by TravisEz13** [comment]
I have a PR open to add the files.  #301 . There are some GitHub issues currently preventing me from testing it.
