### ISSUE TITLE
[Question/Proposal] Azure CLI + PS Core image

### ISSUE THREAD

**Issue by gavinbarron** [PowerShell/PowerShell-Docker#300]
Hi!

In my own workflow I've been making frequent use of PS Core + Azure CLI. Does it makes sense to add a contribution for an image combining these two tools into the Community folder? Or is this something that you would prefer not to have in this repo?

**Comment by RDIL** [comment]
I personally believe that as the purpose of these images is to be slim versions of PS core, that it wouldn't make too much sense to put an unnecessary tool in.  I feel like this would either need to be a sub-image, or not here at all.  This is just my opinion, as it is fully up to @TravisEz13.

**Comment by TravisEz13** [comment]
@RDIL's answer is correct about the purpose of these images.

I see two options:

1. Get enough support for this idea to support a separate image.
2. Add it to the test-deps sub-image
   * But if you do this, please add it to all the supported images, and add a test to verify that it is there.

**Comment by kiazhi** [comment]
I suppose it may have to be on a separate stream if we need it, we will have to install Azure Cli and Az PSModule into image to make it a complete Bash and PowerShell container image that can be switch around.

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Agree with the conclusion @TravisEz13 summarized.  I do recognize that today AzCLI and AzPS don't have parity in capability so sometimes you need AzCLI even if you want to just use AzPS (or vice versa).  The AzCLI and AzPS teams are aware of this and this gap should get smaller over time.

**Comment by RDIL** [comment]
Closing due to lack of discussion.  Anybody else who wants, feel free to comment and I'll reopen it.
