### ISSUE TITLE
Create a debian 11 image

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#307]
## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```sh
> docker info
```

```powershell
> $PSVersionTable
```

**Comment by RDIL** [comment]
on it

**Comment by TravisEz13** [comment]
Debian testing will eventually become debian 11...

**Comment by RDIL** [comment]
What is the LTS codename?

**Comment by RDIL** [comment]
Oh its bullseye okay

**Comment by rhertzog** [comment]
How often are the docker images updated? The `debian:testing` docker image gets updated about once a month IIRC. And we're not referring to a stable release here, but a rolling release ultimately leading to debian 11 in 1.5 years from now.

**Comment by RDIL** [comment]
Every time PowerShell core is released

**Comment by TravisEz13** [comment]
@rhertzog If PowerShell Core has a security release, we update the docker images then.  If not, we usually still have a preview release.  Debian images are usually update every month (although I have not looked at the delay between our creation and theirs, MCR is supposed to be creating an event system so we can rebuild the image every time they update their images.)

**Comment by TravisEz13** [comment]
@rhertzog
