### ISSUE TITLE
Remove the labels

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell-Docker#321]
They are just metadata, and aren't read right now.  I just feel like it would be much cleaner without them.

**Comment by TravisEz13** [comment]
I'll have to follow-up with MCR.  They originally asked us to add them. Following this labeling standard:
http://label-schema.org/rc1/

**Comment by TravisEz13** [comment]
I think all of these are useful
```
LABEL maintainer="PowerShell Team <powershellteam@hotmail.com>" \
      readme.md="https://github.com/PowerShell/PowerShell/blob/master/docker/README.md" \
      description="This Dockerfile will install the latest release of PowerShell." \
      org.label-schema.usage="https://github.com/PowerShell/PowerShell/tree/master/docker#run-the-docker-image-you-built" \
      org.label-schema.url="https://github.com/PowerShell/PowerShell/blob/master/docker/README.md" \
      org.label-schema.vcs-url="https://github.com/PowerShell/PowerShell-Docker" \
      org.label-schema.name="powershell" \
      org.label-schema.vendor="PowerShell" \
      org.label-schema.version=${PS_VERSION} \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vcs-ref=${VCS_REF} \
```

I'm not sure about these
```
      org.label-schema.docker.cmd="docker run ${IMAGE_NAME} pwsh -c '$psversiontable'" \
      org.label-schema.docker.cmd.devel="docker run ${IMAGE_NAME}" \
      org.label-schema.docker.cmd.test="docker run ${IMAGE_NAME} pwsh -c Invoke-Pester" \
      org.label-schema.docker.cmd.help="docker run ${IMAGE_NAME} pwsh -c Get-Help"
```

**Comment by RDIL** [comment]
It says on the official website that this schema is deprecated...

**Comment by TravisEz13** [comment]
and replaced by:
https://github.com/opencontainers/image-spec/blob/master/annotations.md

## Pre-Defined Annotation Keys

This specification defines the following annotation keys, intended for but not limited to [image index](image-index.md) and image [manifest](manifest.md) authors:
* **org.opencontainers.image.created** date and time on which the image was built (string, date-time as defined by [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6)).
* **org.opencontainers.image.authors** contact details of the people or organization responsible for the image (freeform string)
* **org.opencontainers.image.url** URL to find more information on the image (string)
* **org.opencontainers.image.documentation** URL to get documentation on the image (string)
* **org.opencontainers.image.source** URL to get source code for building the image (string)
* **org.opencontainers.image.version** version of the packaged software
  * The version MAY match a label or tag in the source code repository
  * version MAY be [Semantic versioning-compatible](http://semver.org/)
* **org.opencontainers.image.revision** Source control revision identifier for the packaged software.
* **org.opencontainers.image.vendor** Name of the distributing entity, organization or individual.
* **org.opencontainers.image.licenses** License(s) under which contained software is distributed as an [SPDX License Expression][spdx-license-expression].
* **org.opencontainers.image.ref.name** Name of the reference for a target (string).

**Comment by MichaelSimons** [comment]
One of the reasons I dislike labels in general is that they are image metadata and get inherited when you use an image as your base.  Finding images in the wild that have the _PowerShell Team_ as the owner when a third party created the image and didn't 'override' the labels isn't a great UX.

**Comment by TravisEz13** [comment]
Initially MCR said this was a requirement.  Now they say they have no guidance.

It simplifies the images to remove them.
