### ISSUE TITLE
Refactor repository for easier maintaining

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell-Docker#328]
### Summary

We should refactor the repository to function like how `docker-library`'s repositories do.

I am going to use the Python image as an example here.

Port of what the do (basics) to what we can do:
* Each operating system has a `Dockerfile` in `templates/<os name>`
* This template contains all the instructions needed to build a actual Dockerfile
  * The templates are never run directly
* Running `<build tool file> gen` creates the actual images - we could make it use our current folder structure
* Running `<build tool file> build` builds the actual images - we can keep current code for that (mostly)

The point of this update is that we delete/`gitignore` the current structure, and just automate the generation of the current structure.

### Pros

* Only 1 `Dockerfile` needs changing to affect the images
* We can eliminate a lot of the `ARG` layers, because we will just be able to fill in there values when you generate the actual `Dockerfile`s via the templates

### Cons

* May make the build take a few seconds longer

### Conclusion

I think this change is worth it.

I can start doing this if it is accepted, and after #327 is merged (I don't want conflicts in the docs, which will need updating).

**Comment by TravisEz13** [comment]
Can you give links to actual examples?

**Comment by RDIL** [comment]
Sure -
* https://github.com/docker-library/python - the repo
* https://github.com/docker-library/python/blob/master/Dockerfile-alpine.template - example `Dockerfile` template for Alpine
* https://github.com/docker-library/python/blob/master/update.sh - generate real dockerfiles script

**Comment by TravisEz13** [comment]
I don't like this method.  During release builds, the variable has secrets in them.  I don't see how we would make this work.

**Comment by TravisEz13** [comment]
that is, unless we still use the args, and then I don't see the point.

**Comment by RDIL** [comment]
With this, we can have a single Dockerfile, for each image in all 3 official channels, meaning only 1 file needs to be edited to, say, add a dependency.

**Comment by TravisEz13** [comment]
I don't see how.  We would still need a preview, stable, and soon LTS template as the code to produce COULD be different.   Even if they are the same 99% if the time, the 1% breaks this method.

**Comment by RDIL** [comment]
The main motivation for this change is that I feel the build system right now is a bit overcomplicated.  I'm going to try to rewrite some parts of it later tonight.

**Comment by TravisEz13** [comment]
I agree the system is overly complicated, but we need to be sure not to remove features we still need.

Keep in mind that there are basically two build systems, which adds to the complexity.  One for the CI system and one for release builds.  Whatever your write needs to handle both.  This is complicated enough that some design needs to be considered.  Perhaps we should schedule and call.  

Lets look at the requirements:

* Automatic discovery of the latest base image
* Automatic tag name generation
* Injection of the PowerShell package information (URL and name, we have to pull it from a secure internal source when building the official images)
* We will have multiple channels in the future:
  * Preview
  * Current (called stable now)
  * LTS (which could have multiple versions and different images and these will be a long time apart)

**Comment by RDIL** [comment]
Got it.
