### ISSUE TITLE
Provider based Windows Server version 1909 image

### ISSUE THREAD

**Issue by kkbruce** [PowerShell/PowerShell-Docker#341]
NanoServer and ServerCore based image is published to docker hub, 

```powershell
mcr.microsoft.com/windows/nanoserver:1909
mcr.microsoft.com/windows/servercore:1909
```

Could you build tag 1909 version?

**Comment by TravisEz13** [comment]
What do you mean `provider based`?

**Comment by TravisEz13** [comment]
If you are just asking for docker images, please search the repo before filing:  https://github.com/PowerShell/PowerShell-Docker/pull/333

**Comment by kkbruce** [comment]
Yes, I need docker images. I will trace #333 , thanks.
