### ISSUE TITLE
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found.

### ISSUE THREAD

**Issue by zhiweiv** [PowerShell/PowerShell-Docker#347]
## Steps to reproduce
docker run -it --rm mcr.microsoft.com/powershell:6.2.3-debian-stretch-slim pwsh

New-PSSession

## Expected behavior
The cmdlet works

## Actual behavior
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

BTW:
the cmdlet works w/ mcr.microsoft.com/powershell:6.2.3-ubuntu-bionic.

**Comment by TravisEz13** [comment]
libmi requires correct symbolic links to certain libraries for this to work.  Those did not exist in PowerShell 6.2

**Comment by TravisEz13** [comment]
I'd also recommend that you move to SSH based remoting as libmi is no longer supported.
