### ISSUE TITLE
Ubuntu 19.04

### ISSUE THREAD

**Issue by JesterOrNot** [PowerShell/PowerShell-Docker#353]
Was Told to file an issue here by Powershell/Powershell
Name of the Distribution: Ubuntu
Version of the Distribution: 19.04
Processor Architecture (One per request): x86_64

**Comment by RDIL** [comment]
Please link the request issue upstream.

**Comment by JesterOrNot** [comment]
Ok! Please See https://github.com/PowerShell/PowerShell/issues/11507

**Comment by TravisEz13** [comment]
This is an interim release of ubuntu, feel free to add a community image.

**Comment by RDIL** [comment]
Sounds like a good plan to me.  I'll be here to help if you need any @JesterOrNot.
