### ISSUE TITLE
Hi Im looking for help . I need powershell script for deploying microsoft patches on remote machine from standalone machines

### ISSUE THREAD

**Issue by harsharajsalvi** [PowerShell/PowerShell-Docker#36]
Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```sh
> docker info

```

```powershell
> $PSVersionTable

```

**Comment by edyoung** [comment]
@harsharajsalvi I suggest looking on https://gallery.technet.microsoft.com/scriptcenter - this isn't the right place for this question, I'm afraid.
