### ISSUE TITLE
Community Stable CI

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#362]
During the refactor to support LTS releases, the `Community-Stable` name doesn't work anymore.  This raises a few questions.

- ~~The easiest fix is to rename `community-stable` to `community_stable`~~
  - ~~I think this is okay, We only have a couple of contributors and I'm cc`ing you on the change.~~
  - ~~**Actually, I think I have a workaround so we don't have to rename**~~
- Do we want a `community_lts`
  - Until 7.1 is release, both channels will be the same thing.
    So, I think we can defer this.

cc @RDIL, @kiazhi

**Comment by RDIL** [comment]
Bullet one - works for me
Bullet two - no (community images are community maintained, and if people want to use them, they will need to go with the flow.)

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Docker/pull/363

**Comment by TravisEz13** [comment]
Bullet one is resolved.
