### ISSUE TITLE
Add Linux Mint 19.3 Image

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell-Docker#369]
Add Linux Mint 19.3 image.

**Comment by RDIL** [comment]
What package format does it use?  RHEL, PKG, DEB, etc.?

**Comment by ThomasNieto** [comment]
Looks like it uses `apt-get` which would be DEB correct?

https://community.linuxmint.com/tutorial/view/1525

**Comment by RDIL** [comment]
Yup, alright, I can do this on Monday most likely.

**Comment by TravisEz13** [comment]
@ThomasNieto We only have RDIL maintaining community images.  I opened a PR to add the project to up for grabs.
https://github.com/up-for-grabs/up-for-grabs.net/pull/2067
Hopefully, we can get some help.

**Comment by TravisEz13** [comment]
We can no longer support images that the product team doesn't support out of this repo.
