### ISSUE TITLE
Windows powershell

### ISSUE THREAD

**Issue by UrHuckleberry-creator** [PowerShell/PowerShell-Docker#380]
## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```sh
> docker info
```

```powershell
> $PSVersionTable
```

**Comment by UrHuckleberry-creator** [comment]
> ## Steps to reproduce
> ## Expected behavior
> ```
> 
> ```
> 
> ## Actual behavior
> ```
> 
> ```
> 
> ## Environment data
> ```shell
> > docker info
> ```
> 
> ```powershell
> > $PSVersionTable
> ```

**Comment by UrHuckleberry-creator** [comment]
https://github.com/PowerShell/PowerShell-Docker/issues/380#issue-571539114

**Comment by UrHuckleberry-creator** [comment]
`
![IMG_20200223_122849_6](https://user-images.githubusercontent.com/59637081/75370079-6ced4e80-5879-11ea-8c79-734c9edd3cab.jpg)
`

**Comment by TravisEz13** [comment]
closing an empty issue.
