### ISSUE TITLE
[Feature Request] Tag for Azure Devops Windows cached containers

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell-Docker#381]
The current windowsservercore-1809 image has moved ahead of what is cached in the Windows-2019 Azure Devops image. As a result using these containers now take about double the time to initialize as they have to pull the new base image.
https://dev.azure.com/justingrote/Github/_build/results?buildId=691&view=logs&j=913ce52b-8ad3-5a93-c0fe-123235d07c67&t=db8fc2bf-0cbc-4cce-a2f6-5ea7541ec3be&l=57

I recommend a tag name such as: azdevops-windows-2019 that references the base SHA2 hashes for the base images cached by the container listed here:
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#docker-images

Additional Reference:
https://developercommunity.visualstudio.com/content/problem/923295/azure-devops-hosted-windows-containers-take-10-min.html?childToView=931264#comment-931264

**Comment by TravisEz13** [comment]
It's a good idea but not practical.  Unfortunately the user needs to track this.  Whatever we tag will be out of date.
