### ISSUE TITLE
WSC 1803 is EOL, remove the image

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#384]
cc @RDIL

**Comment by RDIL** [comment]
ok, I can do it at ~3:30 my time, which would be I think 11:30 your time 👍

**Comment by TravisEz13** [comment]
No rush...

**Comment by RDIL** [comment]
Nanoserver aswell?

**Comment by RDIL** [comment]
Specifically which images?

**Comment by TravisEz13** [comment]
Windows server core and nanoserver, all channels.
