### ISSUE TITLE
Consider setting the SHELL to pwsh in Docker images

### ISSUE THREAD

**Issue by MichaelSimons** [PowerShell/PowerShell-Docker#394]
Steps to reproduce
------------------

Build the following Dockerfile

```
FROM microsoft/powershell:6.0.1-nanoserver-1709
RUN Get-ChildItem
```

Expected behavior
-----------------

`docker build` would succeed.   I was expecting the SHELL would be set to pwsh in the powershell images.  

`SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]`

This makes it easy to use the PS 'out of the box' in Dockerfiles based on microsoft/powershell.

Actual behavior
---------------

`docker build` fails with the following error

```
Sending build context to Docker daemon  135.7kB
Step 1/2 : FROM microsoft/powershell:6.0.1-nanoserver-1709
 ---> 7dff9740d9d5
Step 2/2 : RUN Get-ChildItem
 ---> Running in f1c4985fd989
'Get-ChildItem' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by TravisEz13** [comment]
Shell is already set as @tehshwann explains it has limited scope.

**Comment by TravisEz13** [comment]
Please file docker image question in PowerShell/PowerShell-Docker for faster triage.

**Comment by TravisEz13** [comment]
When I get time, I am considering changing the entry point and command to have a similar effect.

**Comment by MichaelSimons** [comment]
> I could be mistaken... but I think 'SHELL' only applies to the 'RUN' in the DockerFile.

You are correct.  That is the purpose of the `SHELL` instruction.  The `CMD` and `ENTRYPOINT` instruction do not affect the shell used in the `RUN` instructions.  Setting the `SHELL` would make the PS images more useful as a base image where you want to utilize PS within your Dockerfile

> Shell is already set as @tehshwann explains it has limited scope.

I don't see it set in the PS images.  You can test it out yourself by building the following Dockerfile.  It will fail while running `Get-ChildItem` because it is not being executed within PS.

```
FROM mcr.microsoft.com/powershell:latest
RUN Get-ChildItem
```

I see it [set in the Nano Server Dockerfiles](https://github.com/PowerShell/PowerShell-Docker/blob/master/release/preview/nanoserver1809/docker/Dockerfile#L17) but it is only set in the `installer-env` stage and isn't set in the final stage.

Please consider changing this as it really does make the PS images more useful.

I should also point out if you do consider making this change, it should only be done during the next major/minor release as it should be considered a breaking change.

**Comment by TravisEz13** [comment]
I agree with the change, but it would be a breaking change for customers that assume that the shell is bash or cmd .

**Comment by joeyaiello** [comment]
Had an offline conversation with @TravisEz13. Totally agree that this would be the right thing to do if we were starting fresh, but it's a pretty significant change for both Windows and Linux users.

@MichaelSimons do you or anyone on the .NET team have any experience with making such significant changes to a shipping production container image? Is there some kind of transition path that we can build to make things less (or altogether not) breaking?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  This is too big of a breaking change to accept at this time.  The workaround to set the shell default seems acceptable or calling pwsh explicitly.
