### ISSUE TITLE
Remove Windows 1803 from the Full Tag Listing section on Docker Hub

### ISSUE THREAD

**Issue by MichaelSimons** [PowerShell/PowerShell-Docker#395]
## Steps to reproduce
1.  Navigate to the [PowerShell Docker Hub repo](https://hub.docker.com/_/microsoft-powershell)
2.  View the _Full Tag Listing_ section

## Expected behavior

The tags listed in this section should be supported tags.

## Actual behavior

The Windows 1803 tags are included in the list.  1803 is EOL and should not be listed.  The Dockerfile links for the 1803 entries are broken.

Related to https://github.com/PowerShell/PowerShell-Docker/issues/384

**Comment by MichaelSimons** [comment]
cc @RDIL, @TravisEz13

**Comment by TravisEz13** [comment]
This should be automatic next time we publish images.

**Comment by TravisEz13** [comment]
RDIL has already done this work.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Docker/pull/385
