### ISSUE TITLE
cannot access host by host.docker.internal in windows docker container ?

### ISSUE THREAD

**Issue by felixxuoptovistech** [PowerShell/PowerShell-Docker#397]
repo:
> docker run -it mcr.microsoft.com/powershell cmd
> ping host.docker.internal
   Ping request could not find host host.docker.internal. Please check the name and try again.

![image](https://user-images.githubusercontent.com/57877103/77486813-92c83c00-6e95-11ea-87aa-f78c8cdbfc43.png)

**Comment by TravisEz13** [comment]
This repro is repro'ed in the underlying windows container.  Please contact windows support.

**Comment by TravisEz13** [comment]
Verified in docker run -it mcr.microsoft.com/windowsservercore
