### ISSUE TITLE
Add Docker Image Size to tags table

### ISSUE THREAD

**Issue by TJM** [PowerShell/PowerShell-Docker#405]
Please add the docker image sizes to the image tags table. For some reason the "normal" tags interface on Docker hub was disabled, which lists the compressed size. That is a helpful attribute when choosing which docker image to use. For example, see the tags page for openjdk: https://hub.docker.com/_/openjdk?tab=tags

Thanks in advance,
Tommy

**Comment by TravisEz13** [comment]
Please send this feedback to docker or Microsoft Container Registry.  We are waiting for this feature from those teams.

**Comment by TravisEz13** [comment]
They are asking for feedback here:
https://cloudblogs.microsoft.com/opensource/2019/01/17/improved-discovery-experience-microsoft-containers-docker-hub/

**Comment by TravisEz13** [comment]
Or you can file an issue here: https://github.com/microsoft/containerregistry/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by TravisEz13** [comment]
The issue already exists here:  https://github.com/microsoft/containerregistry/issues/3
