### ISSUE TITLE
Invalid environment variable `LOCALAPPDATA`

### ISSUE THREAD

**Issue by NikolayPianikov** [PowerShell/PowerShell-Docker#410]
The environment variable _LOCALAPPDATA_ was specified like:

https://github.com/PowerShell/PowerShell-Docker/blob/95a36b1d20be7d3b87c85ed89c60a3a54421e381/release/stable/windowsservercore/docker/Dockerfile#L39

for the user _ContainerAdministrator_.
But it should be specified for the user _ContainerUser_. Some applications may crash when accessing this directory with "Access Denied".

**Comment by NikolayPianikov** [comment]
The list of variables:
```
C:\>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\ContainerUser\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=BFEF1206FCBD
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
LOCALAPPDATA=C:\Users\ContainerAdministrator\AppData\Local
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;;C:\Program Files\PowerShell;
PATHEXT=.COM;.EXE;.BAT;.CMD
POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-NanoServer-1909-KB4551762-amd64
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSCORE=\PowerShell\pwsh.exe
PSModuleAnalysisCachePath=\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Windows\TEMP
TMP=C:\Windows\TEMP
USERDOMAIN=User Manager
USERNAME=ContainerUser
USERPROFILE=C:\Users\ContainerUser
windir=C:\Windows
WindowsPATH=C:\Windows\system32;C:\Windows
```

It looks quite strange when `USERNAME=ContainerUser` and 'USERPROFILE=C:\Users\ContainerUser' but `LOCALAPPDATA=C:\Users\ContainerAdministrator\AppData\Local`

**Comment by TravisEz13** [comment]
Looking strange is not a bug.  

The underlying bug is windows doesn't set this.  We are setting it for ContainerAdmin and it's set appropriately.  If you file an issue with windows and they fix the issue, then we can fix this.  For now, This is by design, we have one module cache location of all users.

**Comment by TravisEz13** [comment]
Changing it to what you suggest would just cause the same problem for containers running as containeradmin.  

Please provide full repro information as required in the the issue template.

**Comment by NikolayPianikov** [comment]
## Steps to reproduce

Here is an [example](https://github.com/PowerShell/PowerShell-Docker/files/4509450/issue-410.zip).

## Expected behavior

An application should have an access to its default local application directory.

## Actual behavior

The default local application directory is pointed into non accessible directory and some applications will failed.

## Environment data

Docker info:

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 120
  Running: 2
  Paused: 0
  Stopped: 118
 Images: 406
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.778)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.86GiB
 Name: UNIT-1069
 ID: AF7H:OMJK:IKPR:YUVN:O5LO:CE72:MIIH:TLEV:LB6L:GOW5:HRCP:DFBL
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 50
  System Time: 2020-04-21T13:55:28.6000033+03:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by NikolayPianikov** [comment]
To make the solution acceptable for all users you just could provide an ability to share all required data across all users via common public directory. For instance `C:\Users\Public\...` (and there is an environment variable `PUBLIC=C:\Users\Public` since Windows 7 as I remember) and your image has this directory and this environment variable.

**Comment by TravisEz13** [comment]
Agreed, we should move the module analysis cache to public.

One issue is the use for ContainerUser for nanoserver is deprecated and not supported.  But the same issues should exist on windowsserver core and fixing both is no extra work on our part.
