### ISSUE TITLE
Propsal to remove the script to get tags

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#413]
1. Move all images to floating tags
2. Use dependabot to update floating tags where needed
3. generate our own release specific full tag.

## Status

- [x] Implement system to allow for our own specific full tag
- [ ] Update images
  - [x] Ubuntu 20.04
    - [x] Preview
  - [ ] All others

**Comment by TravisEz13** [comment]
@RDIL 
What do you think about this?

**Comment by RDIL** [comment]
Works for me.

**Comment by TravisEz13** [comment]
The full version should be something like 
```
❯❯❯ (Get-Date).ToString("yyyyddMMHHmm")
202006051309
```

**Comment by TravisEz13** [comment]
@RDIL Up for grabs are supposed to be small tasks...

**Comment by TravisEz13** [comment]
Now that the Engineering system work is done, I think most people can handle the work on images.

**Comment by TravisEz13** [comment]
This is done
