### ISSUE TITLE
Reword the description label to be in terms of an image rather than a Dockerfile

### ISSUE THREAD

**Issue by MichaelSimons** [PowerShell/PowerShell-Docker#427]
## Steps to reproduce

1. `docker pull mcr.microsoft.com/powershell`
1. `docker inspect mcr.microsoft.com/powershell --format "{{ .Config.Labels }}"`

## Actual behavior

There is a `description` label with the following value 

>This Dockerfile will install the latest release of PowerShell.

## Expected behavior

Given this label is applied to an image, I wouldn't expect to see `Dockerfile` terminology.

**Comment by RDIL** [comment]
Can be done with #321

**Comment by TBBle** [comment]
This is probably fixed by #440, which removed the labels entirely.
