### ISSUE TITLE
Executing script through command-line

### ISSUE THREAD

**Issue by manivannanpk** [PowerShell/PowerShell-Docker#464]
This is just a question.

Using PowerShell on Windows or Linux (pwsh), we can execute a script on a Windows target like this:
powershell -File script.ps1 -ip 192.168.1.100 -user administrator -password mypassword
pwsh -File script.ps1 -ip 192.168.1.100 -user administrator -password mypassword

Can this be done using the PowerShell Docker container?

My requirement is to execute this system command from code and process the output of the script. So there is no human intervention.

Thanks,
Mani

**Comment by TravisEz13** [comment]
What you want is 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-7#example-19--run-a-command-on-a-remote-computer-using-ssh

The container will need the SSH client and the server will need SSH remoting setup.

https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#set-up-on-an-ubuntu-1604-linux-computer

**Comment by manivannanpk** [comment]
Thanks for the reply.

Is it not possible to do this without SSH?

<quote>
...the remote computer must be configured with a PowerShell SSH endpoint.
</quote>

Having to do this on all the remote machines would be a problem.
