### ISSUE TITLE
pwsh-preview does not exist in container

### ISSUE THREAD

**Issue by fpfreund** [PowerShell/PowerShell-Docker#49]
Steps to reproduce
------------------
'''Launch newly pushed Linux Container azuresdk/azuer-powershell-core

Expected behavior
-----------------
'''Powershell running in container 

Actual behavior
---------------

c:\docker container run -it  azuresdk/azure-powershell-core
Unable to find image 'azuresdk/azure-powershell-core:latest' locally
latest: Pulling from azuresdk/azure-powershell-core
3b37166ec614: Pull complete
504facff238f: Pull complete
ebbcacd28e10: Pull complete
c7fb3351ecad: Pull complete
2e3debadcbf7: Pull complete
643d5ab5c61e: Pull complete
a8ce5075afa2: Pull complete
13eeea351f16: Pull complete
aedbbd6a1d83: Pull complete
4333ac9a1c63: Pull complete
4bfc231cb25f: Pull complete
8fe9135ed5b4: Pull complete
Digest: sha256:35e4027d51dfef03762492b0091087f9ef1da8ea5f923f208a0ac46dbf03a1b7
Status: Downloaded newer image for azuresdk/azure-powershell-core:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"pwsh-preview\": executable file not found in $PATH": unknown.

Logging into container via --entrypoint "/usr/bin/env" and /bin/sh shows that only /usr/bin/pwsh exists and not pwsh-preview.

```

Environment data
---------------
''docker ce on windows 10 and sles12sp3

<!-- provide the docker info -->

```sh
> docker info

```

```powershell
> $PSVersionTable

```

**Comment by anmenaga** [comment]
Related Azure issue: 
https://github.com/Azure/azure-powershell/issues/7286

**Comment by anmenaga** [comment]
This was fixed in [the source](https://github.com/PowerShell/PowerShell-Docker/commit/dfe64042cd4ead7c8fa57fd06511b08d13978aac#diff-eecef54b8aaa0f94c3b69e09279d1c2e).
@TravisEz13 we probably need to upload the updated ubuntu16.04 image.

**Comment by anmenaga** [comment]
BTW, #40  is a duplicate and mentions a workaround.

**Comment by fpfreund** [comment]
My bad.  I should have perused the other issues prior to opening a new one.   Used a corollary to the workaround to establish an interactive shell within the container to determine cause of the failure.

Apologies for the clutter.
