### ISSUE TITLE
Add alpine v3.12 Image

### ISSUE THREAD

**Issue by podedra92** [PowerShell/PowerShell-Docker#496]
Been waiting a while for 3.11 and now 3.12 is available, 3.10 has security vulnerabilities and  support ends in 6months

**Comment by RDIL** [comment]
#497 removed older versions, and 3.10 will be removed once it is EOL.  I can try to add the new ones later.

**Comment by RDIL** [comment]
3.11 and 3.12 are now the only supported Alpine images by PS docker.
