### ISSUE TITLE
remove 3.10 only for preview (7.1)

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#517]
https://github.com/PowerShell/PowerShell-Docker/tree/master/release/preview/alpine310

**Comment by RDIL** [comment]
What's the reason @TravisEz13?

**Comment by TravisEz13** [comment]
DotNet doesn't support 3.10... this now applies to stable as well

**Comment by RDIL** [comment]
Alright I'll do this

**Comment by RDIL** [comment]
Fixed by #521
