### ISSUE TITLE
no supported WSMan client library was found

### ISSUE THREAD

**Issue by sh0375** [PowerShell/PowerShell-Docker#534]
## Check list

- [X] Verified that this is not a [Known Issue](https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues)
- [ ] Verified this is not an issues in the underlying windows container that should be reported to [Windows Container User Voice](https://windowsserver.uservoice.com/forums/304624-containers)

## Steps to reproduce

```powershell
docker run -it mcr.microsoft.com/powershell
PowerShell 7.1.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

$PSSessionOptionOverride = New-Object System.Management.Automation.Remoting.PSSessionOption -Property  @{'MaximumReceivedObjectSize'=5242880;'Culture'='en-US';'NoMachineProfile'=$true;'CancelTimeout'=150000000;'OperationTimeout'=450000000;'IdleTimeout'=600000000;'OpenTimeout'=150000000;ProxyAccessType=0}
$connectionUri = "https://outlook.office365.com/powershell-liveid/"
$configurationName = "Microsoft.Exchange"
$secPasswd = ConvertTo-SecureString "***" -AsPlainText -Force
$userCredentials = New-Object System.Management.Automation.PSCredential ("***", $secPasswd)
$S1 = New-PSSession -connectionUri $connectionUri -ConfigurationName $configurationName -SessionOption $PSSessionOptionOverride -Credential $userCredentials -Authentication Basic -AllowRedirection -WarningAction SilentlyContinue
```

## Expected behavior

```none

```

## Actual behavior

```none
New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

## Environment data

```sh
> docker info
 docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 2
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /data/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-184-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.857 GiB
Name: ip-172-31-9-35
ID: 3QJA:LUHA:TIAQ:IJK4:V3E2:YRSJ:UD2W:5UP7:CQ7S:QFKH:IS2T:QKJI
Docker Root Dir: /data/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Linux 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
worked with 6.2.3 image that was on my machine (after correcting typo in repro).  pulling and trying latest image

**Comment by Project0** [comment]
I can confirm the problem only exists in the ubuntu 20.04 image, while the ubuntu 18.04 still works

`mcr.microsoft.com/powershell:7.1.0-ubuntu-18.04`: New-PSSession works
`mcr.microsoft.com/powershell:7.1.0-ubuntu-20.04`: New-PSSession fails with missing libraries

**Comment by TravisEz13** [comment]
This is by-design in ubuntu 20.  The library doesn't support PowerShell on Ubuntu 20.

**Comment by Project0** [comment]
> This is by-design in ubuntu 20. The library doesn't support PowerShell on Ubuntu 20.

Aha, do you have more info than this? It is a very inconsistent user experience to not provide the same functionality, just because the distribution version is different.

**Comment by Project0** [comment]
at least i would expect to have a note in the known issues sector and how to fix it.

**Comment by TravisEz13** [comment]
This should be documented in the PowerShell documentation.  The known issue documentation here is for docker specific known issues.  
There is an open doc issue for there here:  https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6491

**Comment by sh0375** [comment]
> at least i would expect to have a note in the known issues sector and how to fix it.

I solved problem installing PSWSMan powershell module which fixes library version.
This is beginning of my Dockerfile:
---------
FROM mcr.microsoft.com/powershell:latest

RUN apt-get update -y
RUN sh -c "yes | pwsh -Command 'Install-Module -Name PSWSMan'"
RUN pwsh -Command 'Install-WSMan'
---------

**Comment by rockonsoft** [comment]
> RUN sh -c "yes | pwsh -Command 'Install-Module -Name PSWSMan'"
> RUN pwsh -Command 'Install-WSMan'

@sh0375 Thanks you so much - that is working for me!!

**Comment by henry123456789101112** [comment]
Tried this but the final command did work for me.
RUN pwsh -Command 'Install-WSMan'
Install-WSMan: The term 'Install-WSMan' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by TravisEz13** [comment]
Please move the conversation about install-wsman to its repo:  https://github.com/jborean93/omi
