### ISSUE TITLE
Image not usable: Enter-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

### ISSUE THREAD

**Issue by SebTardif** [PowerShell/PowerShell-Docker#544]
I saw many speech from Microsoft employee at conferences, about Powershell  is cross OS and awesome, but each couple of years I try,  and it fail flat on the first day.

Just try on Mac, using brew to install and gave: Enter-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

Then I realize I'm kind of using bad habit, I should always use a docker image to do stuff that would require installing things, then I try this image, and it still not working, same problem:

docker run -it mcr.microsoft.com/powershell:preview
PS /> Enter-PsSession –ComputerName server1.domain.com
Enter-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system. 

Good idea versus execution....

**Comment by mdlopresti** [comment]
I'm having the same issue using the mcr.microsoft.com/powershell:lts-debian-10 image

**Comment by TravisEz13** [comment]
The library that supports wsman doesn't support Debian 10.

**Comment by TravisEz13** [comment]
Known issue list updated
https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues#wsman-does-not-work-on-most-linux-images

**Comment by mdlopresti** [comment]
Ubuntu would fit my needs, but 16.04 is pretty old.  Are newer ubuntu images not an option?

**Comment by TravisEz13** [comment]
The OMI which allows WSMan provided by Microsoft no longer supports PowerShell.

I added a link in the known issue to a 3rd party module which adds support for newer distributions.
