### ISSUE TITLE
Issue to track 20H2 support

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PowerShell-Docker#552]
This issue will track when full windows 20H2 support will be back and we can publish those images to ACR. At the moment, we have provided images and corresponding dockerfiles for nanoservercore and windowsservercore 20H2 distributions but can't publish it to ACR. 

An issue has been created on the ACR repo too: https://github.com/Azure/acr/issues/532

## Check list

- [ ] Verified that this is not a [Known Issue](https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues)
- [ ] Verified this is not an issues in the underlying windows container that should be reported to [Windows Container User Voice](https://windowsserver.uservoice.com/forums/304624-containers)

**Comment by TravisEz13** [comment]
Added known issue:
https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues#windows-20h2-images-and-newer

**Comment by vboulineau** [comment]
@anamnavi @TravisEz13 Any news on this? I see that LTSC 2022 has been released, so I guess it's supported in ARC. It'd be nice to support the last SAC as well.

**Comment by TravisEz13** [comment]
We have images available for ltsc2022.  You'll have to ask ACR about their plan to release support for ltsc2022.  We have moved to an internal preview environment to get support early.

**Comment by TravisEz13** [comment]
@anamnavi  plans to add 20H2 images soon.

**Comment by GrumpyMeow** [comment]
I find it quite unfortunate that there's no news on this subject. It feels like ACR is lagging behind and will become end-of-life.
```
ltsc2022: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
20H2: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
```

**Comment by TravisEz13** [comment]
@GrumpyMeow We can support 2022, feel free to submit a PR.

**Comment by vboulineau** [comment]
@TravisEz13 `ltsc2022` is already published on DockerHub, but still nothing for `20H2`. It's not great because `20H2` starts to be used as current SAC by multiple providers, like GKE: https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows#1.20

**Comment by TravisEz13** [comment]
@vboulineau, Great, feel free to submit a PR.  We are still working on getting 2022 support fully out.  We'll work back from there as time allows.

cc @anamnavi, I don't know if you have time to add 20H2 images.

**Comment by vboulineau** [comment]
I think the misunderstanding came from ACR support: it does now support **up to** Windows 2022 (with all versions in between), not only 2022. I've opened the PR to remove the `BrokenFlag` for 20H2 and hopefully it should build successfully.

**Comment by vboulineau** [comment]
Thanks for merging the PR quickly. Is the image publication to `mcr.microsoft.com` automated? Because I don't see the tags there yet: https://mcr.microsoft.com/v2/powershell/tags/list
