### ISSUE TITLE
port Ubuntu 20 and other missing images to LTS

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#558]

**Comment by JustinGrote** [comment]
I assume this includes lts-alpine which is missing?

**Comment by TravisEz13** [comment]
It should.

**Comment by JustinGrote** [comment]
I can take a stab at it :)

**Comment by TravisEz13** [comment]
If you look at it the big change in the docker file is the creation of the symbolic links.
the meta.json drives the build process.  We don't usually do the test-deps images for lts images (but if you want to  include them nothing is stopping you)

many of the parameters are overwritten at build time... if you build locally, use `./build.ps1` (and we are stuck on pester 4.x for now, which is required even for building). Or just use the CI system.

I'm on vacation, but if you look at my GitHub profile, I have several ways of contacting me.  If you get stuck, reach out.

**Comment by JustinGrote** [comment]
@TravisEz13 thanks. A quick question about stable/ubuntu:20.04 - What's with the first build stage of 6.2.4 prior to installing 7?
https://github.com/PowerShell/PowerShell-Docker/blob/d414d3058ce86cf96a3b551c2515a70bb56a437b/release/stable/ubuntu20.04/docker/Dockerfile#L3-L38

**Comment by TravisEz13** [comment]
> many of the parameters are overwritten at build time... if you build locally, use ./build.ps1 (and we are stuck on pester 4.x for now, which is required even for building). Or just use the CI system.

The version number will be overwritten at build time.  Feel free to update it, but we don't regularly update the versions, so they get QUITE out of date.

**Comment by TravisEz13** [comment]
Done
