### ISSUE TITLE
Why aren't all powershell images available for all the windows versions?

### ISSUE THREAD

**Issue by rgl** [PowerShell/PowerShell-Docker#571]
Why aren't all powershell images available for all the windows versions?

For example:

- 7.1.4-windowsservercore is not available for 1809.
  - lts-windowsservercore-1809 is available, but that does not have a version.
- 7.2.0-preview.8-windowsservercore is not available for 1809.
  - the last one was for 7.2.0-preview.2-windowsservercore-1809

And there is no image for the `windows` container flavor. why is that?

**Comment by TravisEz13** [comment]
https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1803-1809-end-of-servicing
1809 reached end of life in May 2021

**Comment by TravisEz13** [comment]
Sorry, https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1809-end-of-servicing
November 2020

**Comment by rgl** [comment]
Sorry, I should have been more explicit, I'm talking about Windows Server 2019 (1809) as-is https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2019 and not Windows Client 10.

**Comment by TravisEz13** [comment]
Feel free to submit a PR.  We have had some blocking issue and we are working from current OSs backwards.
