### ISSUE TITLE
Support openSUSE Leap 15.3

### ISSUE THREAD

**Issue by signed-log** [PowerShell/PowerShell-Docker#600]
I already raised an issue on the powershell repo (PowerShell/PowerShell#16446 and PowerShell/PowerShell#16447)

Create a docker image for openSUSE leap 15.3, based on openSUSE's official container images, which are to be found in their official [container registry](https://registry.opensuse.org)

**Comment by TravisEz13** [comment]
Thanks for filing the issues in the right places.  A PR would be good.... let me see if I can find something close to what you want.

**Comment by Stig124** [comment]
I can PR, will start working on that

**Comment by TravisEz13** [comment]
This is an old image:
https://github.com/PowerShell/PowerShell-Docker/tree/20190919/release/stable/opensuse423
the ps1 file isn't used anymore and there are some changes needed to the metadata ...  
I'm on vacation, but I'll be more than happy to help you through creating a docker image.

**Comment by Stig124** [comment]
Thank you very much,
Just a question, is the `meta.json` file a file manually created or a script is used?

**Comment by TravisEz13** [comment]
manually.
