### ISSUE TITLE
Documentation on hub.docker.com incorrect

### ISSUE THREAD

**Issue by jveldhuijzen** [PowerShell/PowerShell-Docker#612]
Hi,
The documentation on [hub.docker.com](https://hub.docker.com/_/microsoft-powershell?tab=description) states that latest is the 18.04 release of Ubuntu.

If you pull the latest image, you'll get 20.04:
![Ubuntu version after latest has been pulled](https://user-images.githubusercontent.com/74781783/146931898-be9f7e0a-7330-49f9-ac0a-9ef445980656.png)

Please update the documentation on hub.docker.com

**Comment by TravisEz13** [comment]
This was fixed, mention of the version was removed.
