### ISSUE TITLE
CentOS EOL please provide another base like UBI

### ISSUE THREAD

**Issue by delamart** [PowerShell/PowerShell-Docker#614]
The CentOS based images are no longer usable as yum/dnf no longer works:
```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Could you please provide another comparable base image like Red Hat Universal Base Images for example.
Thank you.

**Comment by TravisEz13** [comment]
UBI 8.4 was added

**Comment by delamart** [comment]
Can't find the image in the registry, any idea when it will be available ?
