### ISSUE TITLE
Incorrect Dockerfile Links on dockerhub

### ISSUE THREAD

**Issue by jrdnbradford** [PowerShell/PowerShell-Docker#635]
On [PowerShell DockerHub](https://hub.docker.com/_/microsoft-powershell) the links to the Dockerfiles in this repo are incorrect and need to be updated. It still references directories such as
* `release/lts`
* `release/preview`
* `release/stable`

resulting in `404`s.

**Comment by TravisEz13** [comment]
The last release was done with a9f97ef5f8dfde10dec2f91bab2c67014fef732f which was before the file structure change.  The next release should clear this up.
