### ISSUE TITLE
Cannot pull image `lts-nanoserver-ltsc2022` on Windows 10 21H1 host

### ISSUE THREAD

**Issue by wsy** [PowerShell/PowerShell-Docker#645]
## Check list

- [x] Verified that this is not a [Known Issue](https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues)
- [ ] Verified this is not an issues in the underlying windows container that should be reported to [Windows Feedback Hub](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)  (I'm not sure)

## Steps to reproduce

```powershell
docker run --isolation=hyperv -it mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022 pwsh
```

## Expected behavior
According to [Microsoft Document (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1#windows-client-host-os-compatibility)](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1#windows-client-host-os-compatibility), I shall be able to run ltsc2022 images in Hyper-V isolation mode.
![Windows Client host OS compatibility](https://user-images.githubusercontent.com/2684991/168513272-94cf64fd-a47e-4aaa-bfdc-39bab62be78b.png)

## Actual behavior

I saw an error message saying: 
```none
docker: a Windows version 10.0.20348-based image is incompatible with a 10.0.19043 host.
```

## Environment data

```sh
> docker info
```
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc., v0.8.2)
>   compose: Docker Compose (Docker Inc., v2.5.0)
>   sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
>   scan: Docker Scan (Docker Inc., v0.17.0)
> 
> Server:
>  Containers: 2
>   Running: 1
>   Paused: 0
>   Stopped: 1
>  Images: 17
>  Server Version: 20.10.14
>  Storage Driver: windowsfilter
>   Windows:
>  Logging Driver: json-file
>  Plugins:
>   Volume: local
>   Network: ics internal l2bridge l2tunnel nat null overlay private transparent
>   Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
>  Swarm: inactive
>  Default Isolation: hyperv
>  Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
>  Operating System: Windows 10 Pro Version 2009 (OS Build 19043.1706)
>  OSType: windows
>  Architecture: x86_64
>  CPUs: 8
>  Total Memory: 31.96GiB
>  Name: WSY-PC
>  ID: R2OP:7O2O:KEZC:GBWZ:ONRG:AJUC:HFC4:EOQI:PLDA:UN26:54AL:NPFU
>  Docker Root Dir: C:\ProgramData\Docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
>  Product License: Community Engine

**Comment by TravisEz13** [comment]
You need to ask Windows support about this.
