### ISSUE TITLE
Requires automated Build, Test, Publish for community's Dockerfile contributions

### ISSUE THREAD

**Issue by kiazhi** [PowerShell/PowerShell-Docker#65]
To encourage PowerShell community to contribute in this **PowerShell\PowerShell-Docker** repository, we will need the following capabilities in Azure DevOps Pipelines:

- Build the community's container image in `release/community-stable/` folder
- Test the community's container image with the current test script
- Publish the community's container image to Docker Hub's `pshorg/powershellcommunity` namespace

**Comment by TravisEz13** [comment]
Also, make sure image name is set correctly for community images

**Comment by kiazhi** [comment]
> Also, make sure image name is set correctly for community images

I have fixed the `IMAGE_NAME` value in the Dockerfile in this PR #66 while doing some minor fixes.

**Comment by TravisEz13** [comment]
Yeah, but image name is passed in by the build, so the value in the file has no real effect.

**Comment by TravisEz13** [comment]
Added release build https://github.com/PowerShell/PowerShell-Docker/pull/92
