### ISSUE TITLE
Fedora 35 should be supported as Fedora 34 is EOL

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell-Docker#686]
Fedora 34 is [EOL](https://docs.fedoraproject.org/en-US/releases/eol/).

I would like to request support of Fedora 35.

_See also: #603_

cc: @TravisEz13

**Comment by xtqqczze** [comment]
cc: @daxian-dbw

**Comment by TravisEz13** [comment]
Feel free to add it as a community supported image

**Comment by xtqqczze** [comment]
Issue opened: PowerShell/PowerShell#17849
