### ISSUE TITLE
Upgrade to PowerShell 7.2.6

### ISSUE THREAD

**Issue by robinmalik** [PowerShell/PowerShell-Docker#701]
### Summary of the new feature / enhancement

The latest version of PowerShell is 7.2.6, but `mcr.microsoft.com/powershell:latest` is running 7.2.5.

Please can this be updated, so it doesn't have to be incorporated into the build process?

**Comment by TravisEz13** [comment]
![image](https://user-images.githubusercontent.com/10873629/191600276-d190ee46-44c1-4cad-bea9-ca9344cda9e7.png)

**Comment by robinmalik** [comment]
Awesome, thanks @TravisEz13!
