### ISSUE TITLE
Get-TimeZone -ListAvailable is empty on Ubuntu-22.04

### ISSUE THREAD

**Issue by p0macs** [PowerShell/PowerShell-Docker#702]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

The Ubuntu-22.04 based docker image does not have any timezone info.
The Linux timezones should appear in /usr/share/zoneinfo - but this is empty.
The timezone info is available on the Ubuntu-20.04 based image.

### Expected behavior

```console
Get-TimeZone -ListAvailable | Measure-Object

the Count should be greater than 0
```

### Actual behavior

```console
Get-TimeZone -ListAvailable | Measure-Object

the Count is 0
```

### Environment data

```PowerShell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

7.2.6

**Comment by TravisEz13** [comment]
Please install the timeszones if you want this to work.

**Comment by p0macs** [comment]
Hi. That was my first idea too. But could not do it.
I only found instructions how to change the timezone, and all of them refers to a "timedatectl" command, which is not exists in the image. Looks like you cannot install timedatectl (apt install timedatectl failed), only when you install "systemd" - which is probably not what we wanted - probably there is a good reason why systemd in not in the base image.

I know it is not Powershell topic, but more Ubuntu, but maybe anybody has an idea how to do it?

**Comment by TravisEz13** [comment]
You could also ask .NET as the API we use would be a .NET API
