### ISSUE TITLE
PSGallery is not registered in image 7.2.8 or 7.3.1

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/PowerShell-Docker#728]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

```powershell
docker pull mcr.microsoft.com/powershell:7.3-debian-11
docker pull mcr.microsoft.com/powershell:latest
docker run -it mcr.microsoft.com/powershell:7.3-debian-11
docker run -it mcr.microsoft.com/powershell:latest
```

Run the following in each container:

```powershell
Get-PSRepository
```

### Expected behavior

```console
Returns Nuget and PS Gallery repositories
```

### Actual behavior

```console
Returns warning:


WARNING: Unable to find module repositories.
```

### Error details

```console
N/A
```

### Environment data

```PowerShell
For latest image:


PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


For 7.3.1

```console
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Version

7.2.8, 7.3.1

### Visuals

![image](https://user-images.githubusercontent.com/11204251/211221337-1dc82280-93b0-44da-abc5-de2bba951daf.png)

![image](https://user-images.githubusercontent.com/11204251/211221357-cc5864b0-a813-43bc-86e5-c7156923d41e.png)

**Comment by wsmelton** [comment]
To add even running `Register-PSRepository -Default` does not change the output warning from Get command.

**Comment by wsmelton** [comment]
Issue still exists @TravisEz13 I just pulled the latest image tag and has no repos configured on it.

![image](https://user-images.githubusercontent.com/11204251/227746653-1ed50265-dc6b-4c04-a19c-2d78b98683f6.png)

Do I need to open a new issue since this is 7.3.3?

**Comment by TravisEz13** [comment]
Images are great, but please include things such as digests in text format as well.

Recommendation:  Follow up in the PowerShellGetV2 repo.  Here is a similar issue:  https://github.com/PowerShell/PowerShellGetv2/issues/658

I don't see the digest you got in the manifest for the `latest` tag.

I cannot reproduce your issue.  Be aware that the repositories are registered when **you** run the container.  Do you have any non-default settings for storage or networking in docker. 

![CleanShot 2023-03-30 at 12 47 18@2x](https://user-images.githubusercontent.com/10873629/228948762-4f5be32c-d039-44e4-a04b-c58ffc2c0e5b.png)

I managed to get the digest typed in and it also doesn't repro. 
![CleanShot 2023-03-30 at 12 55 32@2x](https://user-images.githubusercontent.com/10873629/228949828-0c2a9a16-353c-4e41-80c6-541c2284bdcd.png)

**Comment by TravisEz13** [comment]
This issue could also be related:  https://github.com/PowerShell/PowerShellGetv2/issues/350
