### ISSUE TITLE
Colors are not working with `Write-Host`

### ISSUE THREAD

**Issue by GerkinDev** [PowerShell/PowerShell-Docker#745]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

For a CI pipeline (non-interactive), I try to use `Write-Host` with colors, but colors only work in interactive mode.

```sh
docker run --rm -it mcr.microsoft.com/powershell:latest pwsh -c '[System.Enum]::GetValues("ConsoleColor") | ForEach-Object { Write-Host "$_ " -NoNewline; Write-Host "FG " -ForegroundColor $_ -NoNewline; Write-Host "BG " -BackgroundColor $_ }'
```
![image](https://user-images.githubusercontent.com/8212504/228959601-7847352e-0d21-4289-ad8c-7023cf0410ae.png)

```sh
docker run --rm mcr.microsoft.com/powershell:latest pwsh -c '[System.Enum]::GetValues("ConsoleColor") | ForEach-Object { Write-Host "$_ " -NoNewline; Write-Host "FG " -ForegroundColor $_ -NoNewline; Write-Host "BG " -BackgroundColor $_ }'
```
![image](https://user-images.githubusercontent.com/8212504/228959728-edee9606-a95d-43fc-8208-3d35f515642e.png)

The strange thing is that _some commands_ actually print colors in non-interactive mode:
```sh
docker run --rm mcr.microsoft.com/powershell:latest pwsh -c '$PSVersionTable'
```
![image](https://user-images.githubusercontent.com/8212504/228960233-402ef079-13fd-49bb-a7d3-7311ba35ee48.png)

### Expected behavior

```console
Container should output colors, like other containers might do


docker run --rm alpine:latest printf '\e[1;34m%-6s\e[m' 'This is text'


Optionally, this might be forced by a flag
```

### Actual behavior

```console
Text is printed without any colors
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 6.2.8-200.fc37.x86_64 #1 SMP PREEMPT_DYNA…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

7.3.3

### Visuals

In `Steps to reproduce` associated with commands

**Comment by TravisEz13** [comment]
Please run
```
docker run -it --rm mcr.microsoft.com/powershell:latest pwsh -c '[System.Enum]::GetValues("ConsoleColor") | ForEach-Object { Write-Host "$_ " -NoNewline; Write-Host "FG " -ForegroundColor $_ -NoNewline; Write-Host "BG " -BackgroundColor $_ }'
``` 
We cannot figure out how to render colors without a terminal attached.

**Comment by GerkinDev** [comment]
In my CI environment, I **cannot** change those flags. Thus, I have no mean to pass the `-t` flag as you suggest.

**Comment by TravisEz13** [comment]
@JamesWTruher Is there a way to tell us how to render colors, if there is not attached terminal.

**Comment by GerkinDev** [comment]
I don't know the internals of the thing, but what I don't understand either is why PS built-in coloring like `docker run --rm mcr.microsoft.com/powershell:latest pwsh -c '$PSVersionTable'` works without TTY nor anything.

The behavior just seems kind of inconsistent

**Comment by GerkinDev** [comment]
Hi, I don't understand why this issue has been closed, since as mentioned above, there are _some cases_ where colors actually works.

I'm getting out from my comfort zone because I had not manipulated terminals properties for a while, but:
Wouldn't it be possible to determine how to output colors based on some env var, like `TERM` in unix systems, that allows determining the set of ANSI codes usable ?

Thank you

**Comment by GerkinDev** [comment]
Up
