### ISSUE TITLE
Republish Images Without Foreign Layers

### ISSUE THREAD

**Issue by drcapulet** [PowerShell/PowerShell-Docker#756]
### Summary of the new feature / enhancement

Now that Microsoft has [dropped the usage of foreign layers](https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833), would it be possible to get a rebuild of all Windows images please? We use some images based on them and it'll significantly simplify our deploys to air gapped clusters. Thanks!

**Comment by TravisEz13** [comment]
This requires no work on our part.

<img width="724" alt="image" src="https://github.com/PowerShell/PowerShell-Docker/assets/10873629/6eec2796-743e-48af-be69-f05f286a807c">
