### ISSUE TITLE
UBI Dockerfiles have incorrect versions

### ISSUE THREAD

**Issue by flickerfly** [PowerShell/PowerShell-Docker#758]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. Examine the line in the 7.4 release of UBI8 (also on UBI9) determining the version of Powershell installed. See https://github.com/PowerShell/PowerShell-Docker/blob/master/release/7-4/ubi8/docker/Dockerfile#L5
2. Notice the version is based on 7.3, not 7.4.
3. Similarly, notice that the version in 7.3 is using a preview release.

### Expected behavior

```console
When using a Dockerfile in the 7.3 or 7.4 release, I'd expect it to default to a current and non-preview version of Powershell.

I'd expect this to be checked/verified by build pipelines
```

### Actual behavior

```console
Installs an old preview version of Powershell.
```

### Environment data

```PowerShell
I looked at the code in the Dockerfile
```

### Version

5.1.19041.3031

**Comment by TravisEz13** [comment]
the version is an argument, and the build overrides it.  This is not an issue.
