### ISSUE TITLE
The getting started link on the website goes to a nonexistent page. 

### ISSUE THREAD

**Issue by finickydesert** [PowerShell/PowerShell-Docker#767]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

go to the page and clink the link

### Expected behavior

```console
click to get started learning powershell
```

### Actual behavior

```console
github page does not exist
```

### Environment data

```PowerShell
unknown
```

### Version

current

**Comment by TravisEz13** [comment]
Created a PR to resolve this:
https://github.com/PowerShell/PowerShell-Docker/compare/master...update-readme?quick_pull=1

**Comment by TravisEz13** [comment]
Closing this and tracking using the PR.
