### ISSUE TITLE
Running/Building arm64 images on an amd64 host (via QEMU) fails with exit code 132 or 139 (segmentation fault)

### ISSUE THREAD

**Issue by michaelhahn-doka** [PowerShell/PowerShell-Docker#771]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Unfortunately building docker images for arm64 on a build agent (Azure Pipelines) or running them on an amd64 Windows pc with QEMU emulation.
When I run the following:
```
docker run --privileged --rm tonistiigi/binfmt --install arm64 # install arm64 qemu support
docker buildx build --platform linux/arm64 -t my-image-tag . # build arm64 image of Dockerfile
```
for a Dockerfile where the base image is mcr.microsoft.com/powershell:mariner-2.0-arm64 then I always get the following error for all powershell commands used within the Dockerfile.
E.g. `Install-Module -Name "Microsoft.Graph"` results in either exit code 132 or 139 which seems to be a segmentation fault.
When I interactively run a mariner-2.0-arm64 container on an amd64 host with qemu emulation I also get the same error as soon as the interactive shell opens up.

### Expected behavior

```console
It is possible to run powershell commands within the arm64 container when using QEMU
```

### Actual behavior

```console
See steps to reproduce
```

### Environment data

```PowerShell
mcr.microsoft.com/powershell:mariner-2.0-arm64
```

### Version

mcr.microsoft.com/powershell:mariner-2.0-arm64

**Comment by TravisEz13** [comment]
Please read the known issues:
https://github.com/PowerShell/PowerShell-Docker/wiki/Known-Issues#arm-and-qemu-not-supported
