### ISSUE TITLE
Docker images for PowerShell 7.4 (non preview)

### ISSUE THREAD

**Issue by JakobGSvendsen** [PowerShell/PowerShell-Docker#788]
### Summary of the new feature / enhancement

I would like to have non-preview images for PowerShell 7.4

Currently we are using: powershell:7.3-ubuntu-jammy

Do you have any planned date for releasing powershell:7.4-ubuntu-jammy?

**Comment by anamnavi** [comment]
Hi, we are releasing non-preview (7.4) images for PowerShell, including for Ubuntu jammy, can you try this:
docker pull mcr.microsoft.com/powershell:7.4-ubuntu-jammy
