### ISSUE TITLE
Document files and fields for this repo

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#9]
The tags.json is the tag format for the image.

The psVersions.json is the version of PowerShell we will build an image for.

getLatestTag.ps1  returns a structure telling us a tag to build from and how to represent that tag in the tag template.  Here are the properties of the structure:

| Name | description |
|-------|------------|
| Tag     | What we should tag the image |
| Type   | `Full` or `Short`.  Some images have two representations of the same tag.  A full descriptive tag, and short.  Just say which one the 'Tag' property is.  For example for xenial, a short tag would be `xenial` and a long tag would be `xenial-20180525`.|
| FromTag | the tag we should build the image from.  We should try to use the most descriptive tag.  For example for Ubuntu, I would use `xenial-20180525` |

There is a helper [here](https://github.com/PowerShell/PowerShell-Docker/blob/master/tools/getDockerTags/getDockerTags.psm1) which can generate these for you most of the time.

**Comment by RDIL** [comment]
I'll take over this, please assign me.

(maybe we can consider write access in the future, it doesn't allow me to commit to master but does allow me to help out in other ways, eg labeling issues/PRs)

**Comment by TravisEz13** [comment]
thanks
